import { configDotenv } from "dotenv";
configDotenv();
import express from "express";
import connectDB from "./config/db.js";
import cookieParser from "cookie-parser";
import cors from "cors";
import clientRouter from "./routes/clientRoute.js";
import adminsRouter from "./routes/adminsRoute.js";
import assistantRouter from "./routes/assistantRoute.js";
import authRouter from "./routes/authRoute.js";
const app = express();
app.use(cors({ origin: process.env.FRONTEND_URL, credentials: true }));
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cookieParser());
app.use("/api/client", clientRouter);
app.use("/api/assistant", assistantRouter);
app.use("/api/admin", adminsRouter);
app.use("/api/checkAuth", authRouter);
const PORT = process.env.PORT || 3000;
connectDB();
export default app;
